#pragma once

// olc::PixelGameEngine 3.0
// OneLoneCoder 2025

// DO NOT EDIT THIS FILE!
// This file is automatically generated. Changes to source should be made
// through relevant component source file.

//! GRAB GLOBAL STDHEADER

//! GRAB config.h CONFIGURATION

//! GRAB pixel.h DECLARATION

//! GRAB vector2d.h DECLARATION

//! GRAB matrix3d.h DECLARATION

//! GRAB transform2d.h DECLARATION
 
//! GRAB image.h DECLARATION

//! GRAB window.h DECLARATION
 
//! GRAB gpu_iface.h DECLARATION
 
//! GRAB host_iface.h DECLARATION

//! GRAB core.h	DECLARATION







#if OLC_HOST == OLC_HOST_WINDOWS
//! GRAB host_win_winapi.h WINAPI_CONFIG

//! GRAB host_win_winapi.h DECLARATION
#endif

#if OLC_GPU == OLC_GPU_OPENGL33
//! GRAB api_opengl.h OPENGL_CONFIG

//! GRAB api_opengl.h DECLARATION

//! GRAB gpu_opengl33.h DECLARATION
#endif

//! GRAB gputask.h DECLARATION




#if defined(OLC_PGE_APPLICATION) && !defined(PGE_WINDOW_IMPLEMENTED)
//! GRAB window.cpp IMPLEMENTATION 
#define PGE_WINDOW_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_HOST_IMPLEMENTED)
#if OLC_HOST == OLC_HOST_WINDOWS
//! GRAB host_win_winapi.cpp IMPLEMENTATION
#endif
#define PGE_HOST_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_GPU_IMPLEMENTED)
#if OLC_GPU == OLC_GPU_OPENGL33
//! GRAB api_opengl.cpp IMPLEMENTATION
//! GRAB gpu_opengl33.cpp IMPLEMENTATION
#endif
#define PGE_GPU_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_CORE_IMPLEMENTED)
//! GRAB core.cpp IMPLEMENTATION 
#define PGE_CORE_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_IMAGE_IMPLEMENTED)
//! GRAB image.cpp IMPLEMENTATION 
#define PGE_IMAGE_IMPLEMENTED 1
#endif


