#pragma once

// olc::PixelGameEngine 3.0
// OneLoneCoder 2025

// DO NOT EDIT THIS FILE!
// This file is automatically generated. Changes to source should be made
// through relevant component source file.

//! GRAB GLOBAL STDHEADER

//! GRAB config.h CONFIGURATION

//! GRAB pixel.h DECLARATION

//! GRAB vector2d.h DECLARATION

//! GRAB matrix3d.h DECLARATION

//! GRAB transform2d.h DECLARATION

//! GRAB window.h DECLARATION

//! GRAB core.h	DECLARATION


#if defined(OLC_PGE_APPLICATION) && !defined(PGE_WINDOW_IMPLEMENTED)
//! GRAB window.cpp IMPLEMENTATION 
#define PGE_WINDOW_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_CORE_IMPLEMENTED)
//! GRAB core.cpp IMPLEMENTATION 
#define PGE_CORE_IMPLEMENTED 1
#endif
