#pragma once

// olc::PixelGameEngine 3.0
// OneLoneCoder 2025

// DO NOT EDIT THIS FILE!
// This file is automatically generated. Changes to source should be made
// through relevant component source file.

#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>
#include <unordered_map>
#include <iostream>
#include <array>
#include <vector>
#include <memory>
#include <deque>
#include <chrono>

// Version number (accessible as value for incremental comparisons)
#define PGE_VER 300



// Pixel Format in memory 													  
#define PGE_PIXEL_LAYOUT_RGBA 1
#define PGE_PIXEL_LAYOUT_ABGR 2

#if !defined(PGE_PIXEL_LAYOUT)
	#define PGE_PIXEL_LAYOUT PGE_PIXEL_LAYOUT_ABGR
#endif



// Use UK spellings where appropriate
#define PGE_SPELL_CORRECTLY 1
#define PGE_SPELL_INCORRECTLY 2

#if !defined(PGE_SPELLING)
	#define PGE_SPELLING PGE_SPELL_CORRECTLY
#endif

#if !defined(PGE_PIXEL_DECLARED)
namespace olc
{
	class Pixel
	{
	public:
		union
		{
#pragma warning(disable:4201) // Top MSVC whinging about anonymous structs
			struct // Ooooohh be afraid, I'm anonymous! The C++ gremlins will come and get me!
			{
#if PGE_PIXEL_LAYOUT == PGE_PIXEL_LAYOUT_RGBA
				uint8_t r; // 8-bit Red component
				uint8_t g; // 8-bit Green component
				uint8_t b; // 8-bit Blue component
				uint8_t a; // 8-bit Alpha component
#endif

#if PGE_PIXEL_LAYOUT == PGE_PIXEL_LAYOUT_ABGR
				uint8_t a; // 8-bit Alpha component
				uint8_t b; // 8-bit Blue component
				uint8_t g; // 8-bit Green component
				uint8_t r; // 8-bit Red component
#endif
			};
#pragma warning(default:4201)

#if PGE_PIXEL_LAYOUT == PGE_PIXEL_LAYOUT_ABGR			
			//             AABBGGRR
			uint32_t n = 0xFF000000; // 4-Byte AGBR Component
#endif
#if PGE_PIXEL_LAYOUT == PGE_PIXEL_LAYOUT_RGBA
			//             RRGGBBAA
			uint32_t n = 0x000000FF; // 4-Byte RGBA Component
#endif
		};


	public:
		Pixel() = default;

		// Construction via copy
		inline constexpr Pixel(const olc::Pixel& col)
			: n(col.n)
		{ }

		// Construction via copy
		inline constexpr Pixel(const olc::Pixel& col, const uint8_t alpha)
			: n(col.n)
		{		
			a = alpha;
		}


		// Construction via individual channels
		inline constexpr Pixel(const uint8_t red, const uint8_t green, const uint8_t blue, const uint8_t alpha = 0xFF)
			: a(alpha), b(blue), g(green), r(red) 
		{ }

		// Construction via numeric assignment (e.g. #00DDBBFF)
		inline constexpr Pixel(const uint32_t col)
			: n(col)
		{ }

		// Chromatically inverts pixel
		inline constexpr Pixel inv() const
		{
			// Note we must force to a wider signed integer type to prohibit
			// the values wrapping/truncating
			uint8_t nR = uint8_t(std::clamp(255 - int(r), 0, 255));
			uint8_t nG = uint8_t(std::clamp(255 - int(g), 0, 255));
			uint8_t nB = uint8_t(std::clamp(255 - int(b), 0, 255));
			return Pixel(nR, nG, nB, a);
		}

		// Test if two pixels ARE equal
		inline constexpr bool operator==(const Pixel& p) const
		{
			return n == p.n;
		}

		// Test if two pixels ARE NOT equal
		inline constexpr bool operator!=(const Pixel& p) const
		{
			return n != p.n;
		}

		// Compare memory values for use in hashed containers
		inline constexpr bool operator < (const Pixel& p) const
		{
			return n < p.n;
		}

		// Scales pixel colours, except alpha
		template<typename T>
		inline constexpr Pixel operator * (const T i) const
		{
			static_assert(std::is_arithmetic<T>::value, "T must be numeric");
			T fR = std::clamp(r * i, T(0), T(255));
			T fG = std::clamp(g * i, T(0), T(255));
			T fB = std::clamp(b * i, T(0), T(255));
			return Pixel(uint8_t(fR), uint8_t(fG), uint8_t(fB), a);
		}

		// Scales pixel colours, except alpha
		template<typename T>
		inline constexpr Pixel operator / (const T i) const
		{
			static_assert(std::is_arithmetic<T>::value, "T must be numeric");
			T fR = std::clamp(r / i, T(0), T(255));
			T fG = std::clamp(g / i, T(0), T(255));
			T fB = std::clamp(b / i, T(0), T(255));
			return Pixel(uint8_t(fR), uint8_t(fG), uint8_t(fB), a);
		}

		template<typename T>
		inline constexpr Pixel& operator *= (const T i)
		{
			static_assert(std::is_arithmetic<T>::value, "T must be numeric");
			this->r = uint8_t(std::clamp(r * i, T(0), T(255)));
			this->g = uint8_t(std::clamp(g * i, T(0), T(255)));
			this->b = uint8_t(std::clamp(b * i, T(0), T(255)));
			return *this;
		}

		template<typename T>
		inline constexpr Pixel& operator /= (const T i)
		{
			static_assert(std::is_arithmetic<T>::value, "T must be numeric");
			this->r = uint8_t(std::clamp(r / i, T(0), T(255)));
			this->g = uint8_t(std::clamp(g / i, T(0), T(255)));
			this->b = uint8_t(std::clamp(b / i, T(0), T(255)));
			return *this;
		}

		// Adds two pixels, except alpha
		inline constexpr Pixel operator + (const Pixel& p) const
		{
			// Note we must force to a wider signed integer type to prohibit
			// the values wrapping/truncating
			uint8_t nR = uint8_t(std::clamp(int(r) + int(p.r), 0, 255));
			uint8_t nG = uint8_t(std::clamp(int(g) + int(p.g), 0, 255));
			uint8_t nB = uint8_t(std::clamp(int(b) + int(p.b), 0, 255));
			return Pixel(nR, nG, nB, a);
		}

		// Subtracts two pixels, except alpha
		inline constexpr Pixel operator - (const Pixel& p) const
		{
			// Note we must force to a wider signed integer type to prohibit
			// the values wrapping/truncating
			uint8_t nR = uint8_t(std::clamp(int(r) - int(p.r), 0, 255));
			uint8_t nG = uint8_t(std::clamp(int(g) - int(p.g), 0, 255));
			uint8_t nB = uint8_t(std::clamp(int(b) - int(p.b), 0, 255));
			return Pixel(nR, nG, nB, a);
		}

		inline constexpr Pixel& operator += (const Pixel& p)
		{
			// Note we must force to a wider signed integer type to prohibit
			// the values wrapping/truncating
			this->r = uint8_t(std::clamp(int(r) + int(p.r), 0, 255));
			this->g = uint8_t(std::clamp(int(g) + int(p.g), 0, 255));
			this->b = uint8_t(std::clamp(int(b) + int(p.b), 0, 255));
			return *this;
		}

		inline constexpr Pixel& operator -= (const Pixel& p)
		{
			// Note we must force to a wider signed integer type to prohibit
			// the values wrapping/truncating
			this->r = uint8_t(std::clamp(int(r) - int(p.r), 0, 255));
			this->g = uint8_t(std::clamp(int(g) - int(p.g), 0, 255));
			this->b = uint8_t(std::clamp(int(b) - int(p.b), 0, 255));
			return *this;
		}

		// Return RGBA string
		inline std::string str() const
		{
			return std::string("(") + std::to_string(this->r) + "," + std::to_string(this->g) + "," + std::to_string(this->b) + "," + std::to_string(this->a) + ")";
		}
	};

	// Construct pixel from normalised values
	inline constexpr Pixel PixelF(const float red, const float green, const float blue, const float alpha = 1.0f)
	{
		return Pixel(uint8_t(red * 255.0f), uint8_t(green * 255.0f), uint8_t(blue * 255.0f), uint8_t(alpha * 255.0f));
	}


	// C++20 does not recognise these functions as constexpr in std, but this hack
	// works around that restriction.
	namespace internal
	{
		template<typename T>
		constexpr T abs(T v)
		{
			return std::abs(v);
		}

		template<typename T>
		constexpr T fmodf(T v, T u)
		{
			return ::fmodf(v, u);
		}
	}

	// Construct pixel from HSV values
	inline constexpr Pixel PixelHSV(const float h, const float s, const float v, const float alpha = 1.0f)
	{
		const float hue = std::clamp(h, 0.0f, 360.0f);
		const float saturation = std::clamp(s, 0.0f, 1.0f);
		const float value = std::clamp(v, 0.0f, 1.0f);

		const float chroma = value * saturation;
		const float x = chroma * (1.0f - internal::abs(internal::fmodf((hue / 60.0f), 2.0f) - 1.0f));
		const float m = value - chroma;

		float rawRed, rawGreen, rawBlue;

		if (saturation == 0.0f) {
			rawRed = rawGreen = rawBlue = value;
		}
		else if (hue < 60.0f) {
			rawRed = chroma; rawGreen = x; rawBlue = 0.0f;
		}
		else if (60.0f <= hue && hue < 120.0f) {
			rawRed = x;	rawGreen = chroma;	rawBlue = 0.0f;
		}
		else if (120.0f <= hue && hue < 180.0f) {
			rawRed = 0.0f;	rawGreen = chroma;	rawBlue = x;
		}
		else if (180.0f <= hue && hue < 240.0f) {
			rawRed = 0;	rawGreen = x; rawBlue = chroma;
		}
		else if (240.0f <= hue && hue < 300.0f) {
			rawRed = x;	rawGreen = 0.0f; rawBlue = chroma;
		}
		else {
			rawRed = chroma; rawGreen = 0.0f; rawBlue = x;
		}

		return olc::PixelF(rawRed + m, rawGreen + m, rawBlue + m, alpha);
	}

	template<typename T>
	inline constexpr Pixel PixelLerp(const olc::Pixel& p1, const olc::Pixel& p2, const T t)
	{
		static_assert(std::is_floating_point<T>::value, "T must be a floating point type");
		return (p2 * t) + p1 * (T(1) - t);
	}

	// Allow olc::Pixel to play nicely with std::cout	
	inline std::ostream& operator << (std::ostream& os, const olc::Pixel& rhs)
	{
		os << rhs.str();
		return os;
	}

	// A small set of convenient "olc::classic" colour constants
	namespace Colour
	{
		inline constexpr olc::Pixel
			GREY(192, 192, 192), 
			DARK_GREY(128, 128, 128), 
			VERY_DARK_GREY(64, 64, 64),
			RED(255, 0, 0), 
			DARK_RED(128, 0, 0), 
			VERY_DARK_RED(64, 0, 0),
			YELLOW(255, 255, 0), 
			DARK_YELLOW(128, 128, 0), 
			VERY_DARK_YELLOW(64, 64, 0),
			GREEN(0, 255, 0), 
			DARK_GREEN(0, 128, 0), 
			VERY_DARK_GREEN(0, 64, 0),
			CYAN(0, 255, 255), 
			DARK_CYAN(0, 128, 128), 
			VERY_DARK_CYAN(0, 64, 64),
			BLUE(0, 0, 255), 
			DARK_BLUE(0, 0, 128), 
			VERY_DARK_BLUE(0, 0, 64),
			MAGENTA(255, 0, 255), 
			DARK_MAGENTA(128, 0, 128), 
			VERY_DARK_MAGENTA(64, 0, 64),
			WHITE(255, 255, 255), 
			BLACK(0, 0, 0), 
			BLANK(0, 0, 0, 0),
			TANGERINE(255, 165, 0);
	}
}

#define PGE_PIXEL_DECLARED 1
#endif

#if !defined(PGE_VECTOR2D_DECLARED)
namespace olc
{
	/*
		A complete 2D geometric vector structure, with a variety
		of useful utility functions and operator overloads
	*/
	template<class T>
	struct v_2d
	{
		static_assert(std::is_arithmetic<T>::value, "olc::v_2d<type> must be numeric");

		union
		{
#pragma warning(disable:4201) // Top MSVC whinging about anonymous structs
			struct
			{
				// x-axis component
				T x;
				// y-axis component
				T y;
			};
#pragma warning(default:4201)

			std::array<T, 2> xy = { {0,0} };
		};

		// Default constructor
		inline constexpr v_2d() = default;

		// Specific constructor
		inline constexpr v_2d(T _x, T _y) : x(_x), y(_y)
		{}

		// Copy constructor
		inline constexpr v_2d(const v_2d& v) = default;

		// Assignment operator
		inline constexpr v_2d& operator=(const v_2d& v) = default;


		inline constexpr std::array<T, 2> a() const
		{
			return xy;
		}

		// Returns rectangular area of vector
		inline constexpr auto area() const
		{
			return x * y;
		}

		// Returns magnitude of vector
		inline constexpr auto mag() const
		{
			return std::sqrt(x * x + y * y);
		}

		// Returns magnitude squared of vector (useful for fast comparisons)
		inline constexpr T mag2() const
		{
			return x * x + y * y;
		}

		// Returns normalised version of vector
		inline constexpr v_2d norm() const
		{
			auto r = 1 / mag();
			return v_2d(x * r, y * r);
		}

		// Returns vector at 90 degrees to this one
		inline constexpr v_2d perp() const
		{
			return v_2d(-y, x);
		}

		// Rounds both components down
		inline constexpr v_2d floor() const
		{
			return v_2d(std::floor(x), std::floor(y));
		}

		// Rounds both components up
		inline constexpr v_2d ceil() const
		{
			return v_2d(std::ceil(x), std::ceil(y));
		}

		// Returns 'element-wise' max of this and another vector
		inline constexpr v_2d max(const v_2d& v) const
		{
			return v_2d(std::max(x, v.x), std::max(y, v.y));
		}

		// Returns 'element-wise' min of this and another vector
		inline constexpr v_2d min(const v_2d& v) const
		{
			return v_2d(std::min(x, v.x), std::min(y, v.y));
		}

		// Calculates scalar dot product between this and another vector
		inline constexpr auto dot(const v_2d& rhs) const
		{
			return this->x * rhs.x + this->y * rhs.y;
		}

		// Calculates 'scalar' cross product between this and another vector (useful for winding orders)
		inline constexpr auto cross(const v_2d& rhs) const
		{
			return this->x * rhs.y - this->y * rhs.x;
		}

		// Treat this as polar coordinate (R, Theta), return cartesian equivalent (X, Y)
		inline constexpr v_2d cart() const
		{
			return v_2d(std::cos(y) * x, std::sin(y) * x);
		}

		// Treat this as cartesian coordinate (X, Y), return polar equivalent (R, Theta)
		inline constexpr v_2d polar() const
		{
			return v_2d(mag(), std::atan2(y, x));
		}

		// Clamp the components of this vector in between the 'element-wise' minimum and maximum of 2 other vectors
		inline constexpr v_2d clamp(const v_2d& v1, const v_2d& v2) const
		{
			return this->max(v1).min(v2);
		}

		// Linearly interpolate between this vector, and another vector, given normalised parameter 't'
		inline constexpr v_2d lerp(const v_2d& v1, const double t) const
		{
			return (*this) * (T(1.0 - t)) + (v1 * T(t));
		}

		// Compare if this vector is numerically equal to another
		inline constexpr bool operator == (const v_2d& rhs) const
		{
			return (this->x == rhs.x && this->y == rhs.y);
		}

		// Compare if this vector is not numerically equal to another
		inline constexpr bool operator != (const v_2d& rhs) const
		{
			return (this->x != rhs.x || this->y != rhs.y);
		}

		// Return this vector as a std::string, of the form "(x,y)"
		inline std::string str() const
		{
			return std::string("(") + std::to_string(this->x) + "," + std::to_string(this->y) + ")";
		}

		// Assuming this vector is incident, given a normal, return the reflection
		inline constexpr v_2d reflect(const v_2d& n) const
		{
			return (*this) - 2.0 * (this->dot(n) * n);
		}

		// Allow 'casting' from other v_2d types
		template<class F>
		inline constexpr operator v_2d<F>() const
		{
			return { static_cast<F>(this->x), static_cast<F>(this->y) };
		}
	};

	// Multiplication operator overloads between vectors and scalars, and vectors and vectors
	template<class TL, class TR>
	inline constexpr auto operator * (const TL& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs * rhs.x, lhs * rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator * (const v_2d<TL>& lhs, const TR& rhs)
	{
		return v_2d(lhs.x * rhs, lhs.y * rhs);
	}

	template<class TL, class TR>
	inline constexpr auto operator * (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs.x * rhs.x, lhs.y * rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator *= (v_2d<TL>& lhs, const TR& rhs)
	{
		lhs = lhs * rhs;
		return lhs;
	}

	// Division operator overloads between vectors and scalars, and vectors and vectors
	template<class TL, class TR>
	inline constexpr auto operator / (const TL& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs / rhs.x, lhs / rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator / (const v_2d<TL>& lhs, const TR& rhs)
	{
		return v_2d(lhs.x / rhs, lhs.y / rhs);
	}

	template<class TL, class TR>
	inline constexpr auto operator / (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs.x / rhs.x, lhs.y / rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator /= (v_2d<TL>& lhs, const TR& rhs)
	{
		lhs = lhs / rhs;
		return lhs;
	}

	// Unary Addition operator (pointless but i like the platinum trophies)
	template<class T>
	inline constexpr auto operator + (const v_2d<T>& lhs)
	{
		return v_2d(+lhs.x, +lhs.y);
	}

	// Addition operator overloads between vectors and scalars, and vectors and vectors
	template<class TL, class TR>
	inline constexpr auto operator + (const TL& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs + rhs.x, lhs + rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator + (const v_2d<TL>& lhs, const TR& rhs)
	{
		return v_2d(lhs.x + rhs, lhs.y + rhs);
	}

	template<class TL, class TR>
	inline constexpr auto operator + (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs.x + rhs.x, lhs.y + rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator += (v_2d<TL>& lhs, const TR& rhs)
	{
		lhs = lhs + rhs;
		return lhs;
	}

	template<class TL, class TR>
	inline constexpr auto operator += (v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		lhs = lhs + rhs;
		return lhs;
	}

	// Unary negation operator overoad for inverting a vector
	template<class T>
	inline constexpr auto operator - (const v_2d<T>& lhs)
	{
		return v_2d(-lhs.x, -lhs.y);
	}

	// Subtraction operator overloads between vectors and scalars, and vectors and vectors
	template<class TL, class TR>
	inline constexpr auto operator - (const TL& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs - rhs.x, lhs - rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator - (const v_2d<TL>& lhs, const TR& rhs)
	{
		return v_2d(lhs.x - rhs, lhs.y - rhs);
	}

	template<class TL, class TR>
	inline constexpr auto operator - (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return v_2d(lhs.x - rhs.x, lhs.y - rhs.y);
	}

	template<class TL, class TR>
	inline constexpr auto operator -= (v_2d<TL>& lhs, const TR& rhs)
	{
		lhs = lhs - rhs;
		return lhs;
	}

	// Greater/Less-Than Operator overloads - mathematically useless, but handy for "sorted" container storage
	template<class TL, class TR>
	inline constexpr bool operator < (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return (lhs.y < rhs.y) || (lhs.y == rhs.y && lhs.x < rhs.x);
	}

	template<class TL, class TR>
	inline constexpr bool operator > (const v_2d<TL>& lhs, const v_2d<TR>& rhs)
	{
		return (lhs.y > rhs.y) || (lhs.y == rhs.y && lhs.x > rhs.x);
	}

	// Allow olc::v_2d to play nicely with std::cout
	template<class T>
	inline std::ostream& operator << (std::ostream& os, const v_2d<T>& rhs)
	{
		os << rhs.str();
		return os;
	}

	// Convenient types ready-to-go
	typedef v_2d<int32_t> vi2d;
	typedef v_2d<uint32_t> vu2d;
	typedef v_2d<float> vf2d;
	typedef v_2d<double> vd2d;
}
#define PGE_VECTOR2D_DECLARED 1
#endif
//! 
#if !defined(PGE_WINDOW_DECLARED)
namespace olc
{
	class Window
	{
	public:
		Window();
		virtual ~Window();

	public:
		virtual bool OnUserCreate();
		virtual bool OnUserUpdate(float fElapsedTime);
		virtual bool OnUserDestroy();

	public:
		bool olc_ShouldRemove() const;
		bool olc_WindowUpdate(const float fElapsedTime);

	protected:
		bool bShouldRemove = false;
	};
}
#define PGE_WINDOW_DECLARED 1
#endif

#if !defined(PGE_CORE_DECLARED)
namespace olc
{
	// A grouping of all settable PGE properties
	struct PGEConfig
	{
		// Size of "screen" in PGE pixels
		olc::vi2d vScreenSize = { 256, 240 };
		// Size of a PGE pixel
		olc::vi2d vPixelSize = { 4, 4 };
		// Top left location of shown main window
		olc::vi2d vWindowOffset = { 30,30 };
		// Start in full-screen mode
		bool bFullScreen = false;
		// Allow full screen as an option with ALT-ENTER
		bool bFullScreenable = true;
		// Allow teh window to be resized by user
		bool bResizeable = true;
		// Synchronise rendering with monitor
		bool bVSync = false;
		// Behave like a host window, resizing the screen in response to window resize
		bool bRealWindow = false;
		// Ensure aspect ratio of "screen" is mainatined regardless of window size
		bool bRetainAspectRatio = true;
		// Force "screen" pixels to be integer in size
		bool bForceIntegerPixelSize = false;
		// Allow main PGE window to spawn child windows
		bool bAllowChildWindows = true;
	};

	class PixelGameEngine : protected Window
	{
	public:
		PixelGameEngine();
		virtual ~PixelGameEngine();

	public:
		bool Construct(const olc::vi2d& vScreenSize, const olc::vi2d& vPixelSize, bool bFullScreen = false);
		bool Construct(const PGEConfig& config = PGEConfig{});

	public:
		bool Start();

	public:
		bool OnUserCreate() override;
		bool OnUserUpdate(float fElapsedTime) override;
		bool OnUserDestroy() override;

	private:
		void EngineThread();

	private:
		std::deque<std::unique_ptr<Window>> deqChildWindows;

		// Frame Timing & Overall Clocking
		std::chrono::steady_clock::time_point timeFrame1;
		std::chrono::steady_clock::time_point timeFrame2;
		std::chrono::duration<float> durationFrame;
	};
}
#define PGE_CORE_DECLARED 1
#endif


#if defined(OLC_PGE_APPLICATION) && !defined(PGE_WINDOW_IMPLEMENTED)
namespace olc
{
	Window::Window()
	{
	}

	Window::~Window()
	{
	}

	bool Window::OnUserCreate()
	{
		return false;
	}

	bool Window::OnUserUpdate(float fElapsedTime)
	{
		return false;
	}

	bool Window::OnUserDestroy()
	{
		return false;
	}

	bool Window::olc_ShouldRemove() const
	{
		return bShouldRemove;
	}

	bool Window::olc_WindowUpdate(const float fElapsedTime)
	{
		// Environmental changes

		// User Update
		if (!OnUserUpdate(fElapsedTime))
		{
			// User has requested termination of window by returning false
			if (OnUserDestroy())
			{
				// User has confirmed window destruction by returning true
				bShouldRemove = true;
			}
		}

		return false;
	}
};
#define PGE_WINDOW_IMPLEMENTED 1
#endif

#if defined(OLC_PGE_APPLICATION) && !defined(PGE_CORE_IMPLEMENTED)
namespace olc
{
	PixelGameEngine::PixelGameEngine()
	{
	}

	PixelGameEngine::~PixelGameEngine()
	{
	}

	bool PixelGameEngine::Construct(const olc::vi2d& vScreenSize, const olc::vi2d& vPixelSize, bool bFullScreen)
	{
		return false;
	}

	bool PixelGameEngine::Construct(const PGEConfig& config)
	{
		return false;
	}

	bool PixelGameEngine::Start()
	{
		return false;
	}

	bool PixelGameEngine::OnUserCreate()
	{
		return false;
	}

	bool PixelGameEngine::OnUserUpdate(float fElapsedTime)
	{
		return false;
	}

	bool PixelGameEngine::OnUserDestroy()
	{
		return false;
	}

	void PixelGameEngine::EngineThread()
	{
		while (true)
		{
			// Frame Delta Timing - "ElapsedTime" since last core update
			// ~~~~~~~~~~~~~~~~~~
			// All timing is synchronous to the primary window, i.e child
			// windows do not maintain their own frame timing. This is a
			// deliberate decision as PGE will maintain sync between windows.
			// Why? Multiple windows are not really the point of PGE and
			// indeed could just be addional unnecessary complexity. However,
			// by moving to a Window abstraction we kinda get it for free.
			// This freedom comes at the expense of complexity. If we allowed
			// windows to be wholly isolated from the core loop, then the
			// user is expected to maintain thread safety, context sharing
			// and resource management. That is not olc::PGE.

			timeFrame1 = std::chrono::steady_clock::now();
			durationFrame = timeFrame2 - timeFrame1;
			timeFrame1 = timeFrame2;

			// Our time per frame coefficient
			float fDT = durationFrame.count();

			// Primary Window
			olc_WindowUpdate(fDT);

			// Child Windows
			for (auto& winChild : deqChildWindows)
				winChild->olc_WindowUpdate(fDT);

			// Remove child windows that have requested closure
			deqChildWindows.erase(std::remove_if(deqChildWindows.begin(), deqChildWindows.end(),
				[](const std::unique_ptr<Window>& w)
				{
					return w->olc_ShouldRemove();
				}
			));
		}
	}
}
#define PGE_CORE_IMPLEMENTED 1
#endif
